sequenceDiagram
    Publisher->>Publisher: Store Message
    Publisher->>Broker: PUBLISH
    Broker->>Broker: Store Message to "retry"

    Broker->>Subscriber: PUBLISH
    Broker->>Publisher: PUBREC

    Subscriber->>Broker: PUBREC
    Broker->>Subscriber: PUBREL
    Subscriber->>Subscriber: Notify
    Subscriber->>Broker: PUBCOMP


  

    Publisher->>Broker: PUBREL


    Publisher->>Publisher: Delete Message


    rect rgb(200, 255, 200)
      Broker->>Publisher: PUBCOMP
    end
    Note right of Publisher: We do this ! this ensure that the client got notified when the packet is received by an subscriber



    Broker->>Broker: Delete Message
